image: node:10-alpine

stages:
  - build
  - test

build:
  stage: build
  only:
    - master
  tags:
    - ddk.registry
  script:
    - sh build.sh

test:
  stage: test
  only:
    - master
  tags:
    - ddk.registry
  script:
    - sh test.sh
