image: node:10-alpine

stages:
  - test

before_script:
  - apk add python curl bash automake autoconf libtool git alpine-sdk postgresql-dev netcat-openbsd
  - npm i
  - cd ..
  - npm i sodium-native
  - cd ddk.registry

test:
  stage: test
  tags:
    - ddk.registry
  script:
    - npm run test
